# Generated by Django 5.1.1 on 2024-11-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('staff', 'Staff'), ('guest', 'Guest'), ('na', 'N/A')], default='na', max_length=10),
        ),
    ]
