# Generated by Django 5.1.1 on 2024-11-29 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
