# Generated by Django 5.1.1 on 2024-11-25 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_role_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owner',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
        ),
    ]
