# Generated by Django 5.1.2 on 2024-10-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Miscellaneous', max_length=200),
        ),
    ]
