# Generated by Django 5.1.2 on 2024-10-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='No Description', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='exp_date',
            field=models.CharField(default='mm-dd-yy', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='mfg_date',
            field=models.CharField(default='mm-dd-yy', max_length=200),
        ),
    ]
