# Generated by Django 5.1.2 on 2024-10-25 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_product_category'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='Miscellaneous', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.category'),
        ),
    ]
