# Generated by Django 5.1.1 on 2024-10-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exp_date',
            field=models.CharField(blank=True, default='mm-dd-yy', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='mfg_date',
            field=models.CharField(blank=True, default='mm-dd-yy', max_length=200),
        ),
    ]
