# Generated by Django 5.1.2 on 2024-10-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_product_total_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sold_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
