# Generated by Django 5.1.1 on 2024-12-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_notification_owner_alter_product_category'),
        ('dashboard', '0016_alter_product_barcode'),
    ]

    operations = [
    ]
