# Generated by Django 5.1.4 on 2024-12-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_merge_20241201_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='inputted_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
